"""
Compute group-level metrics from ALBERT MGSD baseline full_results,
without having to rerun the entire training.

Usage:
    python compute_group_metrics_albert_mgsd.py
"""

import os
import pandas as pd
from sklearn.metrics import precision_recall_fscore_support, balanced_accuracy_score

# Location of existing results file (generated by baseline_albert_mgsd.py)
FULL_RESULTS_PATH = "../result_output_albertv2/mgsd_trained/mgsd/full_results.csv"


def compute_group_metrics(full_results_path: str) -> pd.DataFrame:
    """Load full_results.csv and compute precision, recall, macro F1 and balanced accuracy per group."""
    if not os.path.exists(full_results_path):
        raise FileNotFoundError(f"full_results not found: {full_results_path}")

    df = pd.read_csv(full_results_path)
    required_cols = {"actual_label", "predicted_label", "group"}
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(f"Missing columns in full_results: {missing}")

    metrics = []
    for group, group_df in df.groupby("group"):
        y_true = group_df["actual_label"]
        y_pred = group_df["predicted_label"]

        precision, recall, f1, _ = precision_recall_fscore_support(
            y_true, y_pred, average="macro", zero_division=0
        )
        balanced_acc = balanced_accuracy_score(y_true, y_pred)

        metrics.append(
            {
                "group": group,
                "precision": precision,
                "recall": recall,
                "f1": f1,
                "balanced_accuracy": balanced_acc,
                "support": len(group_df),
            }
        )

    return pd.DataFrame(metrics).sort_values(by="f1", ascending=False).reset_index(drop=True)


def main():
    df_metrics = compute_group_metrics(FULL_RESULTS_PATH)

    output_dir = os.path.dirname(FULL_RESULTS_PATH)
    output_path = os.path.join(output_dir, "metrics_by_group.csv")
    df_metrics.to_csv(output_path, index=False)

    print("Metrics by group (sorted by F1):")
    print(df_metrics)
    print(f"\nSaved to: {output_path}")


if __name__ == "__main__":
    main()
